feat: OVM
Uniswap/uniswap-v3-core pull request #491
Opened 2021-05-21 07:07 UTC by gakonst

# Summary

The OVM is a sandboxed environment for the EVM which allows execution of smart contract code on L2, with the ability to dispute it on L1 via a fraud proof. Solidity code can be compiled directly to OVM code instead of EVM code by using ["optimistic solc"](https://github.com/ethereum-optimism/solidity), a fork of the well-known solc. The OVM bytecode is ~30% larger than EVM bytecode, which may result in the bytecode being larger than the 24kb size limit for smart contracts.

This PR refactors the codebase to allow it to fit in the 24kb limit, and does a minimal diff to the test suite so that tests can pass when ran against an instance of [go-ethereum running the OVM](https://github.com/ethereum-optimism/optimism/tree/develop/l2geth).
 
# Explanation of code changes

* Introduces a new CI job for the OVM unit tests
* Modifies the hardhat config in the following ways:
    * Overrides the default signer and contracts to always `.wait()`. This is because tests are run against go-ethereum which does not insta-mine, hence receipts are not immediately available in tests.
    * Overrides the default waffle getWallets() method because it fails if the network name is not `hardhat`
    * Makes Waffle fixtures a no-op. This is because go-ethereum does not support snapshots
    * Makes the default ethers provider polling interval 100ms. This is because when blocks don't get instamined, Ethers by default [waits 4s while polling](https://github.com/ethers-io/ethers.js/blob/5f1f2c5e2cb52e15bf88e0ef54efb7b5adc34cca/packages/providers/src.ts/base-provider.ts#L512)
    * Add a new network called `optimism`
    * Increase the mocha timeout, given that there's no fixtures to speed tests up
    * Decreases the optimizer runs to keep bytecode size low
    * Adds a new plugin, `hardhat-ovm` which allows compiling to the OVM when the target network has the `ovm: true` flag set
* Adds a `scripts/run-optimism.sh` script which will clone the Optimism monorepo, build it, and bring up the network
* Replaces the minimal proxy which contains [banned opcodes](https://hackmd.io/elr0znYORiOMSTtfPJVAaA?view#Unsupported-Opcodes) with a normal delegateproxy contract
* Refactors libraries with `internal` functions to `public`, so that they get deployed as separate contracts and do not contribute to the bytecode of the "main" contract. Certain functions were also batched together to minimize the number of `delegatecall`s needed (e.g. `updateAndGetFeeGrowth`). Due to the number of params, some functions required creating intermediate helper structs to help pack the arguments and avoid "stack too deep" errors.

# Status

All tests pass _both_ in the EVM _and_ in the OVM! h/t to @mds1 and @elenadimitrova for the help :)

2021-06-02 16:05 UTC, moodysalem requested changes
can we do something about the modifiers -> functions change?

2021-06-07 19:16 UTC, NoahZinsmeister commented
did a first pass, nothing jumped out to me as a big problem, though i echo what moody already pointed out

2021-06-09 12:50 UTC, gakonst commented on .github/workflows/tests.yml
> +        run: UPDATE_SNAPSHOT=1 yarn test:ovm
We'd need to generate 2 different snapshots since gas costs differ between EVM and OVM (due to including L1 data publishing costs).

2021-06-09 16:35 UTC, moodysalem commented on test/shared/utilities.ts
> + * @notice The OVM emits an additional `Transfer` event due to its usage of WETH instead of native ETH. As a result,
is this transfer the payment of gas?

2021-06-10 06:46 UTC, gakonst commented on test/shared/utilities.ts
> + * @notice The OVM emits an additional `Transfer` event due to its usage of WETH instead of native ETH. As a result,
Yes

2021-06-11 14:23 UTC, merged